/**
 * After a tournament completes, players.json on GitHub is regenerated by a
 * server-side pipeline retriggered by the tournaments.json push (see
 * pushCompletedTournament in github.js). Until that pipeline run finishes, a
 * fresh pull can still fetch pre-tournament ELO — regressing the locally
 * correct value and forcing the user to refresh repeatedly until the pipeline
 * catches up.
 *
 * The local `mexicano_elo_baseline` snapshot (written by
 * finalizeCompletedTournament in tournament.js) must be overlaid onto a
 * freshly pulled players.json summary when it belongs to the latest complete
 * tournament date, so a refresh right after ending a tournament shows the
 * correct ELO immediately instead of a stale value.
 */
import { vi, describe, it, expect, beforeEach } from 'vitest';

// ─── Mock Cache (ephemeral per pull, like production) ────────────────────────

let _cacheData = {};

vi.mock('../../js/cache.js', () => ({
  Cache: {
    get: (key) => _cacheData[key] ?? null,
    set: (key, value) => { _cacheData[key] = value; },
    has: (key) => _cacheData[key] != null,
    del: (key) => { delete _cacheData[key]; },
    keys: (prefix = '') => Object.keys(_cacheData).filter(k => k.startsWith(prefix)),
  },
}));

// ─── In-memory localStorage stub ─────────────────────────────────────────────

function makeLocalStorage() {
  let _store = {};
  return {
    getItem: (key) => Object.prototype.hasOwnProperty.call(_store, key) ? _store[key] : null,
    setItem: (key, value) => { _store[key] = String(value); },
    removeItem: (key) => { delete _store[key]; },
    clear: () => { _store = {}; },
    get length() { return Object.keys(_store).length; },
    key: (i) => Object.keys(_store)[i] ?? null,
  };
}

const ls = makeLocalStorage();
vi.stubGlobal('localStorage', ls);

import { pullForRoute } from '../../js/services/github.js';
import { Store } from '../../js/store.js';

const DATE = '2026-05-12';
const BASE_PATH = 'mexicano_v3/backup-data';
const GH_CONFIG = { owner: 'MinoPlay', repo: 'DataHub_Mexicano', pat: 'test-pat', basePath: BASE_PATH };

function ghB64(obj) { return btoa(JSON.stringify(obj)); }
function ghOk(obj, sha = 'sha1') { return { status: 200, ok: true, json: () => Promise.resolve({ content: ghB64(obj), sha }) }; }
function gh404() { return { status: 404, ok: false, json: () => Promise.resolve({}) }; }

// players.json still reports pre-tournament ELO — the pipeline hasn't run yet.
function makeFetch() {
  return vi.fn(async (url) => {
    if (url.includes('/players.json')) {
      return ghOk([{ Id: 1, Name: 'Alice', ELO: 1000, PreviousELO: 1000, Wins: 0, Losses: 0 }]);
    }
    if (url.includes('/tournaments.json')) {
      return ghOk([{ date: DATE, playerCount: 4, roundCount: 1, matchCount: 1, completedCount: 1, isComplete: true }]);
    }
    if (url.includes(`/${DATE}.json`)) return gh404();
    if (url.includes('/active_tournament.json')) return gh404();
    return gh404();
  });
}

beforeEach(() => {
  _cacheData = {};
  ls.clear();
  Store.setGitHubConfig(GH_CONFIG);
  global.fetch = makeFetch();
});

describe('pull overlays the local elo_baseline snapshot onto a stale players.json', () => {
  it('uses the local post-tournament ELO instead of the not-yet-updated GitHub summary', async () => {
    // Locally, the tournament we just finished computed Alice's ELO to 1016,
    // but players.json on GitHub still has the pre-tournament value (1000)
    // because the data-repo pipeline hasn't finished yet.
    localStorage.setItem('mexicano_elo_baseline', JSON.stringify({
      date: DATE,
      elo: { Alice: 1016 },
      previousElo: { Alice: 1000 },
    }));

    await pullForRoute('#/');

    const summary = Store.getPlayersSummary();
    const alice = summary.find(p => p.name === 'Alice');
    expect(alice.elo).toBe(1016);
    expect(alice.previousElo).toBe(1000);
  });

  it('does not overlay a snapshot for an older, already-superseded tournament date', async () => {
    localStorage.setItem('mexicano_elo_baseline', JSON.stringify({
      date: '2026-04-01', // not the latest complete date
      elo: { Alice: 1234 },
      previousElo: { Alice: 1200 },
    }));

    await pullForRoute('#/');

    const summary = Store.getPlayersSummary();
    const alice = summary.find(p => p.name === 'Alice');
    expect(alice.elo).toBe(1000); // untouched — GitHub value stands
  });

  it('trusts the backend once its pipeline has recomputed a different final ELO for the same date', async () => {
    // The data pipeline already ran and moved players.json's ELO away from the
    // pre-tournament baseline (1000) — but to a value that differs from what
    // finalizeCompletedTournament() computed locally (1016), e.g. because the
    // backend recalculation used a corrected match or different rounding.
    global.fetch = vi.fn(async (url) => {
      if (url.includes('/players.json')) {
        return ghOk([{ Id: 1, Name: 'Alice', ELO: 1005, PreviousELO: 1000, Wins: 0, Losses: 0 }]);
      }
      if (url.includes('/tournaments.json')) {
        return ghOk([{ date: DATE, playerCount: 4, roundCount: 1, matchCount: 1, completedCount: 1, isComplete: true }]);
      }
      if (url.includes(`/${DATE}.json`)) return gh404();
      if (url.includes('/active_tournament.json')) return gh404();
      return gh404();
    });

    localStorage.setItem('mexicano_elo_baseline', JSON.stringify({
      date: DATE,
      elo: { Alice: 1016 },
      previousElo: { Alice: 1000 },
    }));

    await pullForRoute('#/');

    const summary = Store.getPlayersSummary();
    const alice = summary.find(p => p.name === 'Alice');
    // Backend has already moved on — its value must win, not the stale local snapshot.
    expect(alice.elo).toBe(1005);
  });
});
